#!/bin/sh

: ${output_dir:=".generated"}
: ${destination:="sac2016@tera.engr.mun.ca:~/.www"}

rm -rf ${output_dir}
hugo --destination=${output_dir} || exit 1
rm -f ${output_dir}/.DS_Store

rsync -e ssh -avz --delete-after ${output_dir}/ ${destination}/
